-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 20:26:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema InventoryManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InventoryManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InventoryManagement` DEFAULT CHARACTER SET utf8 ;
USE `InventoryManagement` ;

-- -----------------------------------------------------
-- Table `InventoryManagement`.`Users`
-- -----------------------------------------------------
DROP TABLE `InventoryManagement`.`Users`;
CREATE TABLE IF NOT EXISTS `InventoryManagement`.`Users` (
  `UserId` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(25) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InventoryManagement`.`Customers`
-- -----------------------------------------------------
DROP TABLE`InventoryManagement`.`Customers`;
CREATE TABLE IF NOT EXISTS `InventoryManagement`.`Customers` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InventoryManagement`.`items`
-- -----------------------------------------------------
DROP TABLE `InventoryManagement`.`items`;
CREATE TABLE IF NOT EXISTS `InventoryManagement`.`items` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Quantity` INT NULL,
  `Price` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InventoryManagement`.`Transactions`
-- -----------------------------------------------------
DROP TABLE `InventoryManagement`.`Transactions`;
CREATE TABLE IF NOT EXISTS `InventoryManagement`.`Transactions` (
  `Id` INT NOT NULL,
  `ProductId` INT NULL,
  `CustomerId` INT NULL,
  `Price` INT NULL,
  `Quantity` INT NULL,
  `Type` VARCHAR(1) NULL,
  PRIMARY KEY (`Id`),
  INDEX `CustomerId_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `ItemId_idx` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `ItemId`
    FOREIGN KEY (`ProductId`)
    REFERENCES `InventoryManagement`.`items` (`Id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `CustomerId`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `InventoryManagement`.`Customers` (`Id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
